### ISSUE TITLE
Fila med dataSource definisjon skal hete task-manager.properties for å spare sensor for plunder

### ISSUE THREAD

**Issue by asmadsen** [Westerdals/pgr203-assignment-3-boylan157-dagdanmo#2]
https://github.com/Westerdals/pgr203-assignment-3-boylan157-dagdanmo/blob/a4bcfecf0d593870a4399d94fb7cc3b6a6293850/src/main/java/no/kristiania/pgr203/Main.java#L17-L125

**Comment by asmadsen** [comment]
Dere må også bruke `dataSource.url` og `dataSource.username` for å sette URL og User.

**Comment by dagdanmo** [comment]
Fikset.
