### ISSUE TITLE
Testene til DAO skal fange feil dersom DAO ikke lagrer alle felter

### ISSUE THREAD

**Issue by asmadsen** [Westerdals/pgr203-assignment-3-boylan157-dagdanmo#6]
Om noen endrer rekkefølgen på argumentene vil ikke testene feile

https://github.com/Westerdals/pgr203-assignment-3-boylan157-dagdanmo/blob/a4bcfecf0d593870a4399d94fb7cc3b6a6293850/src/main/java/no/kristiania/pgr203/WorkerDao.java#L65-L66

**Comment by dagdanmo** [comment]
Skjønte ikke helt hva du mente her, men vi har oppdaget at vi sliter med å få testene til å feile iblant. Skal prøve å finne ut av det, og ta lærdom.
