### ISSUE TITLE
listAll skulle returnert List<Worker>, ikke List<String>

### ISSUE THREAD

**Issue by jhannes** [Westerdals/pgr203-assignment-3-boylan157-dagdanmo#7]
https://github.com/Westerdals/pgr203-assignment-3-boylan157-dagdanmo/blob/a4bcfecf0d593870a4399d94fb7cc3b6a6293850/src/main/java/no/kristiania/pgr203/WorkerDao.java#L81

Dette vil gi dere problemer til eksamen og dere har ikke helt forstått DAO-pattern. Dere kan velge selv om dere ønsker å rette det før dere leverer på nytt eller ikke.

**Comment by dagdanmo** [comment]
Vi ser hva du mener, og skal få ordnet dette til eksamen! :-)
